### ISSUE TITLE
Problems installing / running in CD runtime container

### ISSUE THREAD

**Issue by vtimd** [tetratelabs/getistio#9]
I attempted to run the commands from the Getting Started Quickly guide via a YAML configuration on a CD platform. This is executing via bash in a container after Terraform deploys the EKS cluster and installs/configures the app via kubectl. 

I'm experiencing issues with the bash profile where it says getistio was install properly, but then it can't find the command.

**Container Image:** 
        - node:12-alpine
      
**Commands listed in YAML:**
        - curl -sL https://tetrate.bintray.com/getistio/download.sh | bash
        - getistio istioctl install --set profile=demo
        - getistio version
        - getistio config-validate
   
**Console Output / Errors:**
```
> curl -sL https://tetrate.bintray.com/getistio/download.sh | bash

Downloading GetIstio from https://tetrate.bintray.com/getistio/getistio_linux_amd64_v1.0.0.tar.gz ...
GetIstio Download Complete!

Error: No user profile found.

Tried $PROFILE (), ~/.bashrc, ~/.bash_profile, ~/.zshrc, ~/.profile, and ~/.config/fish/config.fish.

You can either create one of these and try again or add this to the appropriate file:

export GETISTIO_HOME="$HOME/.getistio"
export PATH="$GETISTIO_HOME/bin:$PATH"
Downloading latest istio ...

Downloading 1.8.2-tetrate-v0 from https://tetrate.bintray.com/getistio/istio-1.8.2-tetrate-v0-linux-amd64.tar.gz ...

Istio 1.8.2 Download Complete!

Istio has been successfully downloaded into your system.

For more information about 1.8.2-tetrate-v0, please refer to the release notes: 
- https://istio.io/latest/news/releases/1.8.x/announcing-1.8.2/

istioctl switched to 1.8.2-tetrate-v0 now
Finished installation. Open a new terminal to start using getistio!
> getistio istioctl install --set profile=demo
/bin/sh: getistio: not found
```

**Comment by vtimd** [comment]
**Attempted Fix**: 
Run `touch ~/.bashrc` before the installation.
**Outcome**: 
Same Error

**Comment by vtimd** [comment]
**Attempted Fix:**
Run `touch ~/.profile` before the installation.
**Outcome:**
Same Error

**Comment by mathetake** [comment]
> Tried $PROFILE (), ~/.bashrc, ~/.bash_profile, ~/.zshrc, ~/.profile, and ~/.config/fish/config.fish.
> You can either create one of these and try again or add this to the appropriate file:
> export GETISTIO_HOME="$HOME/.getistio"
> export PATH="$GETISTIO_HOME/bin:$PATH"

As the message says, could you try `.bash_profile` file? In any case, you could execute `${HOME}/.getistio/bin/getistio` directly.

**Comment by deva26** [comment]
@vtimd - hope this addresses your issue.

**Comment by deva26** [comment]
Shall close this issue as it looks like the concerns are addressed. Please reopen if needed.
